apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-dev
  name: kafka-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-dev
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-dev
    spec:
      containers:
        - env:
            - name: ADV_HOST
              value: 127.0.0.1
            - name: CONNECTORS
              value: elastic, jdbc
            - name: CONNECT_HEAP
              value: 1G
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: RUNTESTS
              value: "0"
            - name: SAMPLEDATA
              value: "0"
          image: lensesio/fast-data-dev:2.5.0
          name: oms-kafka
          ports:
            - containerPort: 2181
            - containerPort: 9092
            - containerPort: 3030
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8083
            - containerPort: 9581
            - containerPort: 9582
            - containerPort: 9583
            - containerPort: 9584
            - containerPort: 9585
          resources: {}
      restartPolicy: Always
status: {}
