apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  serviceName: order-service
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:postgresql://$(POSTGRES_SERVICE_HOST):$(POSTGRES_SERVICE_PORT)/oms-db"
            - name: DB_USER
              value: "username"
            - name: DB_PASSWORD
              value: "password"
            - name: KAFKA_BROKER
              value: "kafka:9092"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
